# Generated by Django 6.0.7 on 2026-08-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Quick ArchRoom Meeting', max_length=200)),
                ('meeting_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('host_name', models.CharField(default='Host', max_length=120)),
                ('guest_name', models.CharField(blank=True, max_length=120, null=True)),
                ('meeting_link', models.URLField(blank=True, default='', max_length=500)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
